module.exports = {
    "Users":
        `uID int (11) auto_increment,
        uLogin varchar(40) default '',
        uPass varchar(32) default '',
        uPass2 varchar(32) default '',
        uPhone varchar(32) default '',
        uState int(1) default 0,
        uAccess int(2) default 0,
        uLang varchar(10) default 'ru',
        uRef int(10) default 0,
        uLTS bigint(14),
        uLIP varchar(15),
        uLSess varchar(32),
        uSuperUsr int(1) default 0,
        PRIMARY KEY(uID),
        UNIQUE KEY ULOGIN(uLogin),
        KEY UREF(uRef),
        KEY ULTS(uLTS)`,
}

/*
$_dbstru = array(

  'Cfg' =>
  "Module varchar(60) ,
  Prop varchar(20),
  Val text,
  UNIQUE KEY  (Module, Prop)",

  'Hist' =>
  "hID int(10) auto_increment,
  hTS bigint(14) default 0,
  hOper varchar(10) default '',
  huID int(10) default 0,
  hIP varchar(15),
  hcID int(2) default 0,
  hSum decimal(36,18) default 0,
  hParams text,
  hTag int(10) default 0,
  hMemo varchar(60),
  hoID int(10) default 0,
  PRIMARY KEY  (hID),
  KEY HTS (hTS),
  KEY HTAG (hTag,hMemo)",

  'Users' =>
  "uID int(10)  auto_increment,
  uGroup varchar(40) default '',
  uLogin varchar(40) default '',
  uPass varchar(32) default '',
  uPass2 varchar(32) default '',
  uTelegLogin varchar(32) default '',
  uTelegId varchar(30) default '',
  uState int(1) default 0,
  uCareerLevel int(2) default 0,
  uCareerStage int(3) default 0,
  uCareerFix int(1) default 0,
  uBTS bigint(14),
  uLevel int(2) default 0,
  uLang varchar(10) default 'ru',
  uMode varchar(10) default '',
  uTheme varchar(10) default '',
  uRef int(10) default 0,
  uClone int(10) default 0,
  uBal decimal(36,18) default 0,
  uBalCount decimal(36,18) default 0,
  uBalWdraw decimal(36,18) default 0,
  uWDDisable int(1) default 0,
  uLTS bigint(14),
  uLIP varchar(15),
  uLSess varchar(32),
  uPTS bigint(14) default 0,
  uBFC int(1) default 0,
  uCodeLogin varchar(6) default '',
  uCodeLoginCount int(1) default 0,
  uCodeLoginTm bigint(14) default 0,
  uSuperUsr int(1) default 0,
  PRIMARY KEY  (uID),
  UNIQUE KEY ULOGIN (uLogin),
  KEY UREF (uRef),
  KEY ULTS (uLTS)",

  'AddInfo' =>
  "auID int(10) ,
  aName varchar(60) default '',
  aName2 varchar(120) default '',
  aCTS bigint(14) default 0,
  aCIP varchar(15) default '',
  aCabinetUsageRestr int(1) default 0,
  aPerc text,
  aDPerc text,
  aPPerc text,
  aIPSec int(1) default 0,
  aSessIP int(1) default 0,
  aSessUniq int(1) default 0,
  aTimeOut int(3) default 0,
  aOIDs text,
  aTZ int(4) default 180,
  aAvatar int(1) default 0,
  aDefCurr int(2) default 0,
  aNoMail int(1) default 0,
  aAgree2 int(1) default 0,
  aPercBlock int(1) default 0,
  aCodeLogin int(1) default 1,
  aNeedReConfig int(1) default 1,
  PRIMARY KEY  (auID)",

  'Currs' => // CID - Currency ID (see psys.php) -> Name, Curr
  "cID int(2)  auto_increment,
  cDisabled int(1) default 1,
  cHidden int(1) default 0,
  cCID varchar(4) default '',
  cCurrID varchar(10) default '',
  cName varchar(120) default '',
  cCurr varchar(60) default '',
  cParams text,
  cParamsSCI text,
  cParamsAPI text,
  cNumDec int(1) default 0,
  cCASHINMode int(1) default 1,
  cCASHINMin decimal(13,6) default 0,
  cCASHINMax decimal(13,6) default 0,
  cCASHINInt int(1) default 0,
  cCASHINComis decimal(6,2) default 0,
  cCASHINComisMin decimal(13,6) default 00,
  cCASHINComisMax decimal(13,6) default 00,
  cCASHOUTMode int(1) default 0,
  cCASHOUTMin decimal(13,6) default 0,
  cCASHOUTMax decimal(13,6) default 0,
  cCASHOUTInt int(1) default 0,
  cCASHOUTComis decimal(6,2) default 0,
  cCASHOUTComisMin decimal(13,6) default 00,
  cCASHOUTComisMax decimal(13,6) default 00,
  cCASHOUTLimitPer int(3) default 0,
  cCASHOUTLimit decimal(13,6) default 0,
  cEXMode int(1) default 0,
  cEXOut decimal(10,6) default 0,
  cEXIn decimal(10,6) default 0,
  cEXMin decimal(13,6) default 0,
  cEXMax decimal(13,6) default 0,
  cEXInt int(1) default 0,
  cEXComis decimal(6,2) default 0,
  cEXComisMin decimal(13,6) default 00,
  cEXComisMax decimal(13,6) default 00,
  cTRMode int(1) default 0,
  cTRMin decimal(13,6) default 0,
  cTRMax decimal(13,6) default 0,
  cTRInt int(1) default 0,
  cTRComis decimal(6,2) default 0,
  cTRComisMin decimal(13,6) default 00,
  cTRComisMax decimal(13,6) default 00,
  cBUYMode int(1) default 0,
  cSELLMode int(1) default 0,
  cBUY2Mode int(1) default 0,
  cSELL2Mode int(1) default 0,
  cGIVEMode int(1) default 0,
  cTAKEMode int(1) default 0,
  cMTS bigint(14),
  cBalMin decimal(13,6) default 0,
  cBal decimal(13,6) default 0,
  cBalTS bigint(14),
  PRIMARY KEY  (cID)", // cParams - IN (public) wallet, cParams2 - OUT (private) wallet

  'Wallets' =>
  "wcID int(2) default 0,
  wuID int(10) default 0,
  wBal decimal(36,18) default 0,
  wLock decimal(36,18) default 0,
  wOut decimal(36,18) default 0,
  wParams text,
  wMTS bigint(14),
  PRIMARY KEY  (wcID,wuID)",

  'Opers' =>
  "oID int(10)  auto_increment,
  oCTS bigint(14),
  oATS bigint(14),
  ouID int(10),
  oOper varchar(10),
  ocID int(2),
  oSum decimal(36,18) default 0,
  oComis decimal(36,18) default 0,
  oParams text,
  oParams2 text,
  oBatch varchar(40),
  oTag varchar(60),
  oTS bigint(14),
  oState int(1) default 0,
  oPTS bigint(14) default 0,
  oMemo varchar(120),
  oNTS bigint(14),
  PRIMARY KEY  (oID),
  KEY OBATCH (ocID,oBatch),
  KEY OTAG (oTag)", // oParams2 - additional parameters (for ex. deposit)

  'Queue' =>
  "qiID int(10)  auto_increment,
  qID int(2),
  quID int(10) default 0,
  qMax int(1) default 0,
  PRIMARY KEY (qiID),
  KEY QUID (quID)",

  'Career' =>
  "ruID int(10),
  rState int(1) default 0,
  rStage int(3) default 0,
  rFixState int (1) default 0,
  rCTS bigint(14) default 0,
  rSum decimal(36,18) default 0,
  rBonusLvl int(2) default 0,
  rMaxStage int(3) default 0,
  rParam text default '',
  PRIMARY KEY RUID (ruID)",

  'OpersAdd' =>
  "bID int(10) auto_increment,
  boID int(10),
  buID int (10),
  bcID int(2),
  bSum decimal(36,18) default 0,
  bComis decimal(36,18) default 0,
  bAcc text default '',
  PRIMARY KEY BID (bID)"
);
*/